version: '3.9'

services:
  redis:
    container_name: redis-cache
    image: redis
    environment:
     - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"] 

  postgres:
    container_name: pg-db-movies
    image: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=docker
     - POSTGRES_DB=movies
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
